name: Automatically approve pull requests
on:
  pull_request_target:
    branches:
      - main
      - alpha
      - beta
      - development
      - gh-pages
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'lengors'
    steps:
      - uses: hmarr/auto-approve-action@v3
